// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkH0FTXgJFiCoIe8lqC1KyqUL_MbSNw8',
    appId: '1:383226856498:web:7122c3d65ad2a6874fa82b',
    messagingSenderId: '383226856498',
    projectId: 'work-cafe-4d491',
    authDomain: 'work-cafe-4d491.firebaseapp.com',
    storageBucket: 'work-cafe-4d491.appspot.com',
    measurementId: 'G-RJHPGV2N9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhv4XdV8jyEICUiAPtNYeIrofyUEF1pt8',
    appId: '1:383226856498:android:ef17c51c6ee93b854fa82b',
    messagingSenderId: '383226856498',
    projectId: 'work-cafe-4d491',
    storageBucket: 'work-cafe-4d491.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9FegfBptD571I0TKjfkJMvsMvOEsLc2c',
    appId: '1:383226856498:ios:25a1d8c2baff0df54fa82b',
    messagingSenderId: '383226856498',
    projectId: 'work-cafe-4d491',
    storageBucket: 'work-cafe-4d491.appspot.com',
    iosClientId: '383226856498-goi52shi72shmkkvrruqpec87pt3f4d1.apps.googleusercontent.com',
    iosBundleId: 'com.workcafe.workcafe',
  );
}
